### ISSUE TITLE
unnecessary dependency virtualenv

### ISSUE THREAD

**Issue by Ismail-Maj** [fvaleye/metadata-guardian#22]
# Description
Hello! I've seen that you use `virtualenv` in several places (docker, documentation...). 
I was wondering if it was necessary, python has already a built-in virtual environment, I think that
```
$ pip install virtualenv
$ virtualenv venv
```
can safely be replaced with 
```
$ python -m venv venv
```

**Comment by fvaleye** [comment]
Hello @Ismail-Maj!

Thank you for submitting this issue.

You are right, the `virtualenv` dependency is not required, I created the PR #23 to improve it 👍
